#' Wraps ggplot2 for pretty default plots with subset highlighted
#'
#' A nice long description.
#'
#' @usage mmplot_selection(data, x, y, logx, logy, selection)
#'
#' @param plot A plot generated by mmplot.
#' @param sel A subset selection of the mmplot.
#' 
#' @return a ggplot2 object
#' 
#' @export
#' @import ggplot2
#' @author Soren M. Karst \email{smk@@bio.aau.dk}
#' @author Mads Albertsen \email{MadsAlbertsen85@@gmail.com}

mmplot_selection <- function(plot=p,sel=sel){
  s <- plot + geom_polygon(data=sel, aes(x=sel[,1], y = sel[,2]), size = .5, color = "darkred", fill = NA, linetype= 2) +
    geom_point(data=sel, aes(x=sel[,1], y = sel[,2]), size = 2, color = "black")  
  return(s)
}
